[package]
name = "gol-be"
version = "0.1.0"
authors = ["Robin van Leeuwen <robin@mintlab.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.5", features = "postgres" }
dotenv = "0.15.0"